sridhiraj/SUBSCRIPTION_SYSTEM

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SubscriptionController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Customer.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Order.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Subscription.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/SubscriptionRatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MultipleRatePlanDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubscriptionDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubscriptionInOut.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/SubscriptionRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/specification/SubscriptionSpecification.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java
backend/HCL-BSS/src/main/resources/application.properties

Hi Aditya, Plz review & merge Subscription Search related changes in DEV_PH1.

Dev subscription search

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/BatchController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/BatchDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/BatchRunLogDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/FilterRequest.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/BatchLogRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/specification/BatchLogSpecification.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/BatchLogService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/BatchLogServiceImpl.java

Batch Report APIs

---

backend/HCL-BSS/src/main/java/com/hcl/bss/constants/ApplicationConstants.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Customer.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Order.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Product.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Subscription.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/SubscriptionRatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/SubscriptionRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/BillingInvoiceScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/ProductServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanServiceImpl.java

code changes for billing invoicing

Code review branch

---

backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Order.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Product.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java

code changes for addon subscription

code changes for addon product subscription creation

---

backend/HCL-BSS/src/main/java/com/hcl/bss/constants/ApplicationConstants.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/User.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/DropDownOutDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/UserDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/UserInDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/UserOutDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/UserRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/specification/UserManagementSpecification.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServices.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

Hi Aditya,
Please review & merge this UserManagement poll request.

UserManagement Implementation

---

backend/HCL-BSS/src/main/java/com/hcl/bss/constants/ApplicationConstants.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/DownloadRecordController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/ProductController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/RatePlanController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SubscriptionController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/CSVRecordDataDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/DownloadCsvInputDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/ProductDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/ProductPlanAssociationDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RatePlanDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RatePlanProductDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RatePlanVolumeDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/ProductService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/ProductServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java
backend/HCL-BSS/src/main/resources/application.properties

Dev ph1 export to csv

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SsRestApplication.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/ProductRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/BillingInvoiceScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/ProductServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Compilation issue merge

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/RatePlanController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Currency.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RatePlanDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/CurrencyMasterRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/ProductServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanServiceImpl.java

Kindly review and merge changes for add a rate plan

Added Service for Add Rate Plan

---

backend/HCL-BSS/src/main/java/com/hcl/bss/constants/ApplicationConstants.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SsRestApplication.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Customer.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Notification.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RenewalBatchLog.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Subscription.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/SubscriptionRatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/AppConstantRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/CustomerRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/NotificationRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/RenewalBatchLogRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/BillingInvoiceScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionRenewalScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/ProductServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/util/SubscriptionUtility.java
backend/HCL-BSS/src/main/resources/application.properties

adding code changes for subscription auto renewal

autorenewal changes

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SsRestApplication.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionRenewalScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/util/SubscriptionUtility.java

fixes for subscription auto renewal

Subscription autorenewal

---

backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java

code fix for subscription autorenewal

code fix for subscription autorenewal

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/BatchController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/RatePlanController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/ProductServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanServiceImpl.java

Rate plan break fix

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SsRestApplication.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/specification/SubscriptionSpecification.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Subscription Search Issue Resolved

Dev subscription search issues

---

backend/HCL-BSS/src/main/java/com/hcl/bss/constants/ApplicationConstants.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/BatchController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/ProductController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/RatePlanController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SubscriptionController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/AddressDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/CustomerDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubscriptionDetailDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubscriptionRatePlanDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomGlobalExceptionHandler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomSubscriptionException.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/BatchLogServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Subscription detail

---

backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Subscriptionsearchissuefixes

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Menu.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Role.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/SubMenu.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/User.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MenuAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubMenuAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/UserAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomGlobalExceptionHandler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomUserMgmtException.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServices.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

RoleBased Story- getAuthorizationDetail service implementation

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MenuAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

GetAuthorizationDetail Api Response is Modified

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SubscriptionController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Order.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Product.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Subscription.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/SubscriptionRatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MenuAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionRenewalScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

enhancements and bug fixes

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SsRestApplication.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/SubscriptionRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/NotificationScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/RatePlanServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

AssociatePlanIssue fixed

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/CSVRecordDataDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServices.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

UserManagementExportCSvForSearchApi

---

backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Dev role based

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/BatchController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/DashboardController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/ProductController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/RatePlanController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Auditable.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RatePlan.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/DashboardGraphDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/GraphRequestDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubscriptionDetailDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomGlobalExceptionHandler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/SubscriptionRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/specification/SubscriptionSpecification.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/BillingInvoiceScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionRenewalScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/SubscriptionScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DashBoardService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DashBoardServiceImpl.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Dashboard graph and bug fixes

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/RoleMenuMapping.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MenuAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MenuDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/ProfileInDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RoleInDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RoleMenuDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RoleOutDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomGlobalExceptionHandler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/MenuRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/RoleMenuMappingRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/RoleRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/SubMenuRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServices.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

User Profile three service

---

backend/HCL-NOTIFICATION/pom.xml
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/client/BSSClient.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/config/ActiveMQConfig.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/config/DBConnectionConfig.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/config/SwaggerConfig.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/controller/NotificationApplication.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/controller/NotificationController.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/dto/AddressDto.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/dto/BatchDto.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/dto/BatchRunLogDto.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/dto/CustomerDto.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/dto/SubscriptionDetailDto.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/dto/SubscriptionRatePlanDto.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/email/sender/EmailNotificationProducer.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/email/sender/EmailSender.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/email/service/EmailContentBuilder.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/email/service/EmailService.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/email/service/EmailServiceImpl.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/messaging/producer/SmsNotificationProducer.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/messaging/producer/SmsSender.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/CreateTopicRouteBuilder.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/MyBean.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/MyProcessor.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/NotificationReceiver.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/NotificationSender.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/SampleCamelRouter.java
backend/HCL-NOTIFICATION/src/main/resources/application.properties
backend/HCL-NOTIFICATION/src/main/resources/templates/subscription_mail_notification.html

Notification without routing

---

backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubscriptionDetailDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/SubscriptionRatePlanDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Email notification fixes

---

backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Subscription.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

Changed cancel date type from Date to LocalDate

Rate plan landing page service

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MenuAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RoleMenuDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/UserAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomGlobalExceptionHandler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/MenuRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/RoleMenuMappingRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/SubMenuRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServices.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

getAuthorizationDetail issue fix, deleteRoleMapping implemented

---

backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

Dev role based new

---

backend/HCL-BSS/src/main/java/com/hcl/bss/security/CustomUsernamePasswordAuthenticationFilter.java

added the code to send the response of menu and sub menu

updating CustomUsernamePasswordAuthenticationFilter file

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/UserRoleMapping.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/MenuDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/ProfileInDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RoleMenuDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/UserAuthDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomGlobalExceptionHandler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/exceptions/CustomUserMgmtException.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/UserRoleMappingRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServices.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

Dev profile based

---

backend/HCL-NOTIFICATION/pom.xml
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/client/BSSClient.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/email/service/EmailServiceImpl.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/SampleCamelRouter.java
backend/HCL-NOTIFICATION/src/main/resources/application.properties
backend/HCL-NOTIFICATION/src/main/resources/templates/subscription_mail_notification.html

Notification with routing

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SsRestApplication.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SubscriptionController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/NotificationScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/security/SecurityConfig.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/DownloadRecordServiceImpl.java

Email notification changes for routing

---

backend/HCL-BSS/src/main/java/com/hcl/bss/constants/ApplicationConstants.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/domain/User.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/UserInputDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/RoleRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/UserRoleMappingRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServices.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

Changes for roleId removal from tb_user_details table

---

backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

Profile delete issue

---

backend/HCL-BSS/src/main/java/com/hcl/bss/domain/Role.java

DeleteRoleMenuMapping issue

---

backend/HCL-BSS/src/main/java/com/hcl/bss/services/UserServicesImpl.java

Dev code cleanup

---

backend/HCL-BSS/src/main/java/com/hcl/bss/dto/CustomerDto.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

commit for sms notification

---

backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/EmailProcessor.java
backend/HCL-NOTIFICATION/src/main/java/com/hcl/bss/notification/routes/ExceptionProcessor.java

Exception handling

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/UserManagementController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/dto/RoleInputDto.java

Get AllMenuSubmenu Change Request Resolved

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SubscriptionController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/repository/SubscriptionRepository.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/NotificationScheduler.java
backend/HCL-BSS/src/main/java/com/hcl/bss/security/SecurityConfig.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionService.java
backend/HCL-BSS/src/main/java/com/hcl/bss/services/SubscriptionServiceImpl.java

notification changes

---

backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/FileUploadDownloadRestController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/controllers/SubscriptionController.java
backend/HCL-BSS/src/main/java/com/hcl/bss/schedulers/NotificationScheduler.java

crossfilterissuefixed
